# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_author', models.CharField(max_length=100)),
                ('subreddit_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('comment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('subreddit', models.CharField(db_index=True, max_length=100)),
                ('author_flair_text', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('link_title', models.CharField(db_index=True, max_length=100)),
                ('link_id', models.CharField(db_index=True, max_length=100)),
                ('body', models.TextField(db_index=True)),
                ('body_html', models.TextField()),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('created_utc', models.DateTimeField(db_index=True)),
                ('link_url', models.URLField()),
                ('parent_id', models.CharField(db_index=True, max_length=100)),
                ('date_stored', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
