# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0006_partial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_flair_text', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_utc', models.DateTimeField(db_index=True, null=True)),
                ('date_saved', models.DateTimeField(db_index=True, null=True)),
                ('author', models.TextField(null=True)),
                ('author_user_id', models.TextField(db_index=True, null=True)),
            ],
            options={
                'ordering': ('-created_utc',),
            },
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('subreddit_id', models.TextField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('savable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='storage.Savable')),
                ('comment_id', models.TextField(blank=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField()),
                ('body_html', models.TextField()),
                ('parent_id', models.TextField(db_index=True)),
            ],
            bases=('storage.savable',),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('savable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='storage.Savable')),
                ('submission_id', models.TextField(blank=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, db_index=True, null=True)),
                ('num_comments', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('permalink', models.TextField(blank=True, null=True)),
                ('post_hint', models.TextField(blank=True, null=True)),
            ],
            bases=('storage.savable',),
        ),
        migrations.AddField(
            model_name='savable',
            name='saved_by',
            field=models.ManyToManyField(related_name='savable_set', to='social_django.UserSocialAuth'),
        ),
    ]
