# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIdentity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedditProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_user_id', models.TextField(db_index=True, null=True, unique=True)),
                ('username', models.TextField(null=True, unique=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reddit_accounts.LocalIdentity')),
            ],
        ),
    ]
