const constants = {
    REQUEST_SAVED: "REQUEST_SAVED",
    RECEIVE_SAVED: "RECEIVE_SAVED",
    REQUEST_SUBREDDITS: "REQUEST_SUBREDDITS",
    RECEIVE_SUBREDDITS: "RECEIVE_SUBREDDITS",
    TOGGLE_SELECTED: "TOGGLE_SELECTED",
    REMOVE_SELECTED: "REMOVE_SELECTED",
    TOGGLE_SAVED: "TOGGLE_SAVED",
    SEARCH_SAVED: "SEARCH_SAVED",
    REQUEST_USER: "REQUEST_USERS",
    RECEIVE_USER: "RECEIVE_USER",
    SORT_COLORS: "SORT_COLORS",
    SEARCH_VALUE_CHANGED: "SEARCH_VALUE_CHANGED"
}

export default constants