const constants = {
    REQUEST_SAVED: "REQUEST_SAVED",
    RECEIVE_SAVED: "RECEIVE_SAVED",
    TOGGLE_SAVED: "TOGGLE_SAVED",
    SEARCH_SAVED: "SEARCH_SAVED",
    REQUEST_USER: "REQUEST_USERS",
    RECEIVE_USER: "RECEIVE_USER",
    SORT_COLORS: "SORT_COLORS",
}

export default constants